### ISSUE TITLE
noteフィールドの表示位置について

### ISSUE THREAD

**Issue by Gedevan-Aleksizde** [ShiroTakeda/jecon-bst#10]
現在は bookで `note`, 及び `url` (または`doi`)フィールドが邦訳情報の後に表示されます (添付ファイル参照). 
これに関して, 以下のような変更を希望します.
1. 原著に対する情報が邦訳情報の後に来るのは不自然なので, 「url/doi」, 「note」, 「邦訳書情報」の順に表示する
2. 添付例のように, 邦訳に対する注釈を別途書くため, 邦訳情報の括弧内の末尾に表示できる補足説明 `jnote` フィールドを新たに用意する

修正前の例
[example-old.pdf](https://github.com/ShiroTakeda/jecon-bst/files/4871766/example-old.pdf)
修正後の例
[example-mod.pdf](https://github.com/ShiroTakeda/jecon-bst/files/4871767/example-mod.pdf)

私は学術論文というより(一般向けの)技術文書の作成のために使っているため, なるべく邦訳情報を正確に書きたいということでこのように希望しているだけで, このフォーマットが何かの手続きに必須というわけではありません. もちろん趣旨にそぐわないというのであれば却下していただいてかまいません. 承諾していただけるならPRを出します.

**Comment by ShiroTakeda** [comment]
邦訳書情報はこれまで自分では利用する機会があまりなく、いいかげんな処理にしていましたので、ご希望のように変更するのでかまいません。

プルリクエストを出してもらえるのでしたらお願いします。

**Comment by ShiroTakeda** [comment]
マージをしておきました。

かなり適当に書いているプログラムなのでわかりにくかったのではないかと思います。特に、jecon.bst内で定義しているformat.namesという関数が

"xxx" jauthor format.names * "訳" *

のように変な引数をとるのが不思議に思われるかもしれませんが、この "xxx" というのはダミーの引数を無理やりつけているだけです。

とにかく、ありがとうございました。
