### ISSUE TITLE
year, authorがないmiscエントリーでのエラー・警告

### ISSUE THREAD

**Issue by estshorter** [ShiroTakeda/jecon-bst#13]
例えば、以下のbibファイルを
``` bib
@misc{web,
	title={google},
	url={https://google.com},
	access={2020/8/11}
}
```

以下のtexファイルで引用したとき、`pbibtex`の実行時にエラー・警告が出ます。[miscはauthor, yearがなくてもよいはず](http://www.yamamo10.jp/yamamoto/comp/latex/bibtex/bibtex.html)なので、対応いただけると大変助かります。
なお、エラーを吐いていてもbblファイルは正常に生成されます。
``` tex
\documentclass[a4paper]{jsarticle}
\usepackage{natbib}
\bibliographystyle{jecon}
\begin{document}
引用\cite{web}
\bibliography{references}
\end{document}
```

実行ログは下記のとおりです。 jecon.bstは d6b3c7718cfd01aee14f595f319525a2f4e191ff を使用しました。
``` bat
> platex main.tex
（省略）

> pbibtex main
This is pBibTeX, Version 0.99d-j0.33 (utf8.euc) (TeX Live 2020/W32TeX)
The top-level auxiliary file: main.aux
The style file: jecon.bst
(guessed encoding: UTF-8 = utf8)Database file #1: references.bib
`year' is a missing field, not a string, for entry web
while executing---line 4796 of file jecon.bst
ptr=1, stack=

---the literal stack isn't empty for entry web
while executing---line 4796 of file jecon.bst
`year' is a missing field, not a string, for entry web
while executing---line 4800 of file jecon.bst
`year' is a missing field, not a string, for entry web
while executing---line 4800 of file jecon.bst
Warning--empty author in web
Warning--there's no year in web
Warning--empty year in web
(There were 4 error messages)
```

**Comment by ShiroTakeda** [comment]
返答がおそくなりすみません。

これなのですが、エラーが出ないように修正しようと思いましたが、year と author が指定されていることが前提の部分が多くて、思ったより修正が難しそうです。たぶんできるとは思いますが、ちょっと検討してみます。

**Comment by ShiroTakeda** [comment]
補足です。

misc タイプの文献では必須のフィールドがなく、authorとyearフィールドを省略可能というのはご指摘の通りです。

ただ、（jecon.bstのように）natbib package との併用を前提とする bst ファイルは、元々「author-year」形式の引用形式を前提としています。というか、元々 author-year の引用形式をおこなうために natbib package が開発されたのだと思います。

author-year 形式の引用を前提としているため、authorフィールド、yearフィールドには必ず値が指定されていることを前提としています。

他のフィールドに値が指定されていない場合の処理でしたら、それほど難しくないのですが、以上の理由から author と year が指定されていないというときの処理は案外ややこしくなってしまいます。

**Comment by estshorter** [comment]
ご回答ありがとうございます。

> ただ、（jecon.bstのように）natbib package との併用を前提とする bst ファイルは、元々「author-year」形式の引用形式を前提としています。というか、元々 author-year の引用形式をおこなうために natbib package が開発されたのだと思います。

そういった経緯があったのですね。でしたら、仕様ということで本issueはcloseして頂いても構いません。

**Comment by ShiroTakeda** [comment]
エラーが出ると途中で止まって、正常に出力できないことが多いのですが、一応出力はできているようですので、それではいったんcloseさせていただきます。

一応、検討はしたいと思いますので、直せたら直したいと思います。
