### ISSUE TITLE
【不具合報告】remove.irrelevant.kutoten の不具合？

### ISSUE THREAD

**Issue by ryoya9826** [ShiroTakeda/jecon-bst#14]
添付しました sample.pdf におきまして，（bst.use.unicode の引数を #1 にしたうえで）upbibtex を使用すると，邦訳書の情報をつけるときに jnote を省略すると jyear のあとの「，」が省略されないようです．

以下のサンプルは ，同梱の jejon.bst を bst.use.unicode の引数を #1 に変更する改変を施した ujecon.bst を用いて作成しました．

[sample.zip](https://github.com/ShiroTakeda/jecon-bst/files/5848675/sample.zip)

**Comment by ShiroTakeda** [comment]
ありがとうございます。確認しました。また、jauthor の名前が

名無 , 権兵衛訳

のように区切りのカンマが入ってしまう点もおかしいようです。多分どちらもすぐ直せると思います。

**Comment by ShiroTakeda** [comment]
↓のjecon.bstで修正しました。

https://github.com/ShiroTakeda/jecon-bst/blob/develop/jecon.bst

もし問題がありましたら言ってください。

**Comment by ryoya9826** [comment]
確認しました．
おかげさまで所望の結果を得ることができました．
本IssueはCloseさせていただきます．
