### ISSUE TITLE
TeXファイル内で「sec:hoyakusho」が二重に定義されている

### ISSUE THREAD

**Issue by massongit** [ShiroTakeda/jecon-bst#18]
```
LaTeX Warning: Label `sec:hoyakusho' multiply defined.
```

`jecon-example.tex` 内で `\label{sec:hoyakusho}` が二重に定義されているため、コンパイルすると上記の Warningが発生します。

<定義されている箇所>
https://github.com/ShiroTakeda/jecon-bst/blob/86a0791342187383e4fb685dfcab8b72112e8be0/jecon-example.tex#L403
https://github.com/ShiroTakeda/jecon-bst/blob/86a0791342187383e4fb685dfcab8b72112e8be0/jecon-example.tex#L457-L458

**Comment by ShiroTakeda** [comment]
ありがとうございます。修正したいと思います。

**Comment by massongit** [comment]
ご対応ありがとうございました。
https://github.com/ShiroTakeda/jecon-bst/commit/ef2ac4e4cbbe0c738c4d27564b79250dfbd48ae9 で修正されたようなのでcloseします。
