### ISSUE TITLE
日本語文献における、DOIの前後に付与される文字列に関するバグ

### ISSUE THREAD

**Issue by estshorter** [ShiroTakeda/jecon-bst#2]
日本語文献においても、DOIの前後に付与される文字列に英語文献用のものが使用されてしまう。
jecon.bst中ではbst.doi.pre.jpが一か所しか存在しないので、日本語文献の判定をしてbst.doi.pre.jpを使うようにする命令が抜け落ちている？

**Comment by ShiroTakeda** [comment]
どうもありがとうございます。

日本語文献に bst.doi.pre.jp & bst.doi.post.jp を使うようになっていませんでした。DOI付きの日本語文献を例に入れていなかったので気づきませんでした。修正したいと思います。
