### ISSUE TITLE
ライセンスの明文化

### ISSUE THREAD

**Issue by pecorarista** [ShiroTakeda/jecon-bst#4]
ライセンスの明確な記載がありませんが、どのようになっているのでしょうか。
直近では jecon.bst を含む論文のソースファイルの公開に問題がないか気になっています。
また TeX Live に入っているとうれしいという気持ちがあり、そういうことを考えるとライセンスが明確になっていたほうがよいと思います。

`jecon.bst` ファイル本体のコメントを見る限りいろいろ方が関わっているようで、
決めることが難しいかもしれませんが、ご対応いただけるとありがたいです。

**Comment by ShiroTakeda** [comment]
元々、ちゃんと配布するようなことを想定していなかったので、TeX Liveで配布できるようなライセンスにしていないです。他の bst ファイルを参考にしたところもあり、曖昧な部分もあるのですが、ちゃんとしたライセンスに変更することも検討したいと思います。ライセンスを変更したら一応TeX Liveでの配布もできると思います。

**Comment by pecorarista** [comment]
ご回答ありがとうございます。
ご検討よろしくお願いいたします。
