### ISSUE TITLE
DOI に TeX の制御文字が含まれる場合の処理

### ISSUE THREAD

**Issue by Gedevan-Aleksizde** [ShiroTakeda/jecon-bst#6]
DOI に, URL では使われるが TeX では制御文字として扱われるためにエスケープする必要がある文字が含まれる場合, 正しく表示されません. まれなケースですが, 以下のようにアンダースコアを含む DOI に出くわしました. mendeley や zotero 等の文献管理ソフト側ではDOIに含まれる TeX 制御文字をエスケープしないため, bst ファイル側で調整したほうが良いと思います.

この問題を修正したプルリクエストをお送りしてよろしいでしょうか? `url.sty` にのみ依存した修正案なので影響も最小限だと思います.

## 現在
![2019-10-13T223322](https://user-images.githubusercontent.com/8291043/66716534-b7f65000-ee09-11e9-868c-83d5ca7f5844.png)

## 修正した結果
![2019-10-13T223119](https://user-images.githubusercontent.com/8291043/66716535-b9c01380-ee09-11e9-922b-1fda9217ac54.png)

## bib ファイル

[underscores.bib.txt](https://github.com/ShiroTakeda/jecon-bst/files/3721799/underscores.bib.txt)

**Comment by ShiroTakeda** [comment]
はい。お願いします。取り込みますので。

**Comment by ShiroTakeda** [comment]
mergeしました。他にも何かありましたら言ってください。
