### ISSUE TITLE
【機能要望】文献一覧での自動の et al./他 の付与

### ISSUE THREAD

**Issue by akira-okumura** [ShiroTakeda/jecon-bst#9]
学生の日本語修論用にありがたく研究室内で使わせていただいています。

現在 `bst.and.others.num` の設定では本文中の引用で自動的に et al. などを付与するようになっていますが、論文末尾の文献一覧では全著者が何人いても表示されるようになっています。私の物理・天文系の分野では著者人数が 1000 を超えることも珍しくなく、出版社の BiBTeX ファイルを学生がそのまま使用すると、1 つの文献だけで何ページも紙面を割いてしまう場合があります。

投稿論文用に出版社の用意するものだと自動的に et al. が表示される `.bst` ファイルが多いと思うのですが、`jecon.bst` でも同様の機能を持たせられないでしょうか。

もちろん `.bib` ファイルを編集して `and others` とすれば解決する話なのですが、もし `jecon.bst` 側でも対応できると、大変助かります。

**Comment by ShiroTakeda** [comment]
著者数が多い場合には文献一覧（reference）部分でも著者名を省略するということでしたら比較的簡単な修正でできると思いますので、修正してみたいと思います。

ただ、私自身の研究分野（経済学系）では著者数はせいぜい数名程度のことがほとんどで、著者数が非常に多い論文に私はあまりなじみがありませんので、いくつか実装について確認させていただきたいです。

1) 省略する場合はEinstein et al. のように第一著者だけ表示する形でよいでしょうか？

2) 何人以上の著者がいるときに省略するようにすればよいでしょうか？
これは選択可能な設定にしたいと思いますが、一応、目安になるでフォールトの値があれば教えていただきたいです。

またできれば適当な文献の例（bibデータ）を紹介していただければありがたいです（もし可能でしたら日本語文献も）。

**Comment by akira-okumura** [comment]
ご検討ありがとうございます。

### A1
これは出版社・論文誌によって違うのですが、

- _N_ 人以上の場合は Author1 et al. とする（Physical Review Letters など）
- _N1_ 人以上の場合は _N2_  人までは表示し Author1, Author2, Author3, et al. とする（Astrophysical Journal など）

の 2 通りがあります。そのため、変数としては _N1_ と _N2_ の 2 つがあると確実で、前者の場合は _N2_ = 1 とした特殊例だとみなしてユーザで設定できると汎用的かなと思います。

### A2
網羅的に調べていませんが、_N2_ = 3 が一般的ではないかと経験的に思います。

Bib ファイルの例ですが、例えば
https://doi.org/10.1016/j.physletb.2012.08.020
のページ最上部の Export から。

または
http://dx.doi.org/10.3847/2041-8205/826/1/L13
の Abstract の直後にある Export citation and abstract から入手可能です。

日本語だと限られた著者人数での解説記事くらいしか存在しない分野ですので、日本語文献例は思いつきません。著者が数十人を超えるような物理・天文系の日本語文献は存在しないのではないかと思います。

他に必要情報があれば、お知らせください。

**Comment by akira-okumura** [comment]
Astrophysical Journal の場合、Overleaf `aasjournal.bst` を含むテンプレートがあります。
https://ja.overleaf.com/latex/templates/aastex-template-for-submissions-to-the-astrophysical-journal/bpkjwktvsqwp

**Comment by ShiroTakeda** [comment]
情報ありがとうございます。だいたいわかりました。

可能であれば

N1 人以上の場合は N2 人までは表示し Author1, Author2, Author3, et al. とする（Astrophysical Journal など）

という形にしたいと思います。

aasjourna.bstを参考に修正してみます。少しお待ちください。

**Comment by ShiroTakeda** [comment]
修正をしてみました。以下のブランチに置いています。

https://github.com/ShiroTakeda/jecon-bst/tree/develop

著者がN1人以上の場合はN2 人まで表示するという形にしました。N1とN2はそれぞれ以下の関数で設定しています。

N1: bst.max.author.num で設定（デフォールト値は 8）
N2: bst.max.author.num.display で設定（デフォールト値は 3）

試しに

https://github.com/ShiroTakeda/jecon-bst/blob/develop/customization/bib_with_many_authors.bib

の文献を扱ってみましたが、とりあえずは上手く動いているようです。

https://github.com/ShiroTakeda/jecon-bst/blob/develop/customization/jecon-many-authors.tex
https://github.com/ShiroTakeda/jecon-bst/blob/develop/customization/jecon-many-authors.pdf

ただ、一つ問題があります。上の文書にも書いたのですが、TeX Live 2019の pbibtex では著者数があまりに多いと処理できないようです。TeX Live 2020の pbibtex でしたら問題はありません。

よろしければうまく動くかどうか試していただけないでしょうか？問題や要望がありましたら言ってください。

**Comment by akira-okumura** [comment]
ありがとうございます。
https://github.com/akira-okumura/MasterThesisTemplate
にて使用し、期待通りの動作をすることを確認いたしました。お忙しいところありがとうございました。

今年度の修論で学生数名が使用しますので、何か使用中に気がつく点があれば、またここでお伝えしたいと思います。
